### ISSUE TITLE
setup.py looks for pandoc in weird place

### ISSUE THREAD

**Issue by tripleee** [akissa/spamc#4]
When there is no `pandoc` installed, I get

```
vnix$ pip install path/to/spamc
Unpacking path/to/spamc
  Running setup.py egg_info for package from file:///path/to/spamc
    sh: /weird/odd/path/bin/pandoc: not found
```

It seems there is a bug in `setup.py` -- it loops over `PATH` looking for `pandoc`, but if it's never found, it proceeds anyway, using the last component of the `PATH`.

**Comment by akissa** [comment]
Fix committed da4cca3
